# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20171121_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='duration_format',
            new_name='duration_type',
        ),
    ]
